[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sme-dataprep"
version = "0.1.0"
description = "Educational data preprocessing utilities for SME coursework."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  {name = "Aimar Barrena Pol"}
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Education",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Information Analysis",
]
dependencies = [
  "numpy>=1.24",
  "pandas>=2.0",
  "matplotlib>=3.7"
]

[project.optional-dependencies]
dev = [
  "jupyter>=1.0"
]

[project.urls]
Homepage = "https://github.com/abarrenap/sme-dataprep-python"
Repository = "https://github.com/abarrenap/sme-dataprep-python"
Issues = "https://github.com/abarrenap/sme-dataprep-python/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["dataprepkit*"]
